name: iOS Deploy
on:
 workflow_dispatch:
    branches:
      - master
    paths:
      - ''

jobs:
  deploy:
    name: Build IPA
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Dependencies
        run: yarn install

      - name: Build Archive
        uses: yukiarrr/ios-build-action@v1.3.0
        with:
          project-path: 'live2d-demo.xcodeproj'
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          p12-base64: Automatic
          mobileprovision-base64: Automatic
          team-id: ${{ secrets.TEAM_ID }}
          output-path: Live2d.ipa
          certificate-password: "1"
          export-method: "ad-hoc"
